//
//  TextKey.swift
//  concertjournal
//
//  Created by Paul Arbetit on 20.02.26.
//

import Foundation

// MARK: - String Keys Enum

enum TextKey: String {
    
    // MARK: - App General
    case appName                    = "app.name"
    
    // MARK: - Actions
    case cancel                     = "action.cancel"
    case save                       = "action.save"
    case delete                     = "action.delete"
    case confirm                    = "action.confirm"
    case skip                       = "action.skip"
    case done                       = "action.done"
    case close                      = "action.close"
    case reload                     = "action.reload"
    case retry                      = "action.retry"
    case retryAgain                 = "action.retry_again"
    case allow                      = "action.allow"
    case understood                 = "action.understood"
    case `import`                   = "action.import"
    case openSettings               = "action.open_settings"
    case openInMaps                 = "action.open_in_maps"
    case openOriginalLink           = "action.open_original_link"
    case openCamera                 = "action.open_camera"
    case chooseFromGallery          = "action.choose_from_gallery"
    case logOut                     = "action.log_out"
    case resetSetup                 = "action.reset_setup"
    case goToSettings               = "action.go_to_settings"
    case generateNewCode            = "action.generate_new_code"
    case restorePurchases           = "action.restore_purchases"
    case sortieren                  = "action.sort"
    case search                     = "action.search"
    case showAll                    = "action.show_all"
    case editSetlist                = "action.edit_setlist"
    case addSetlist                 = "action.add_setlist"
    case addTicket                  = "action.add_ticket"
    case addPhotos                  = "action.add_photos"
    case addPhotoLater              = "action.add_photo_later"
    case addTravelInfo              = "action.add_travel_info"
    case changeTravelInfo           = "action.change_travel_info"
    case addBuddy                   = "action.add_buddy"
    case addSupportAct              = "action.add_support_act"
    case addCompanion               = "action.add_companion"
    case editCompanion              = "action.edit_companion"
    case edit                       = "action.edit"
    case createConcert              = "action.create_concert"
    case createWithTicket           = "action.create_with_ticket"
    case createManually             = "action.create_manually"
    case enterAllDetailsManually    = "action.enter_all_details_manually"
    case importFromSpotify          = "action.import_from_spotify"
    case loginWithSpotify           = "action.login_with_spotify"
    case sendResetLink              = "action.send_reset_link"
    case login                      = "action.login"
    case register                   = "action.register"
    case premiumBecome              = "action.premium_become"
    case premiumUnlock              = "action.premium_unlock"
    case nextStep                   = "action.next_step"
    case nextStepExclamation        = "action.next_step_exclamation"
    case letsGo                     = "action.lets_go"
    case letsGoExclamation          = "action.lets_go_exclamation"
    case keepGoing                  = "action.keep_going"
    case almostDone                 = "action.almost_done"
    case allReady                   = "action.all_ready"
    case sendFriendRequest          = "action.send_friend_request"
    case requestAlreadySent         = "action.request_already_sent"
    case endFriendship              = "action.end_friendship"
    case alreadyBuddies             = "action.already_buddies"
    case friendWithoutAccount       = "action.friend_without_account"
    case removeYes                  = "action.remove_yes"
    case previewLabel               = "action.preview_label"
    case scanTicket                 = "action.scan_ticket"
    case scanTicketAuto             = "action.scan_ticket_auto"
    case scanning                   = "action.scanning"
    case hidePrices                 = "action.hide_prices"
    case showPrices                 = "action.show_prices"
    
    // MARK: - Navigation Titles
    case navConcerts                = "nav.concerts"
    case navMap                     = "nav.map"
    case navBuddies                 = "nav.buddies"
    case navProfile                 = "nav.profile"
    case navPremium                 = "nav.premium"
    case navFilter                  = "nav.filter"
    case navBuddyAdd                = "nav.buddy_add"
    case navRequests                = "nav.requests"
    case navVenueSelect             = "nav.venue_select"
    case navTicketScan              = "nav.ticket_scan"
    case navTicketInfo              = "nav.ticket_info"
    case navEditConcert             = "nav.edit_concert"
    case navImportConcert           = "nav.import_concert"
    case navImportSpotify           = "nav.import_spotify"
    case navTravelInfo              = "nav.travel_info"
    case navSongSelect              = "nav.song_select"
    case navNewPassword             = "nav.new_password"
    case navForgotPassword          = "nav.forgot_password"
    case navQrScan                  = "nav.qr_scan"
    case navOrderCustomize          = "nav.order_customize"
    case navBrowse                  = "nav.browse"
    case navAttendees               = "nav.attendees"
    case navAppColor                = "nav.app_color"
    case navDebugLogs               = "nav.debug_logs"
    
    // MARK: - Home Screen
    case homeTitle                  = "home.title"
    case homeNoConcerts             = "home.no_concerts"
    case homeAddFirst               = "home.add_first"
    case homeAddFirstCta            = "home.add_first_cta"
    case homeUpcomingConcerts       = "home.upcoming_concerts"
    case homePastConcerts           = "home.past_concerts"
    case homeConcertsThisYear       = "home.concerts_this_year"
    case homePlannedThisYear        = "home.planned_this_year"
    case homeToday                  = "home.today"
    case homeOfflineWarning         = "home.offline_warning"
    
    // MARK: - Concert Creation / Edit
    case concertCreateHow           = "concert.create_how"
    case concertDelete              = "concert.delete"
    case concertDeleteQuestion      = "concert.delete_question"
    case concertDeleteConfirm       = "concert.delete_confirm"
    case concertImported            = "concert.imported"
    case concertEntry               = "concert.journal_entry"
    
    // MARK: - Concert Detail Fields
    case fieldArtist                = "field.artist"
    case fieldVenue                 = "field.venue"
    case fieldVenueOptional         = "field.venue_optional"
    case fieldSelectVenue           = "field.select_venue"
    case fieldDate                  = "field.date"
    case fieldSelectDate            = "field.select_date"
    case fieldNotes                 = "field.notes"
    case fieldRating                = "field.rating"
    case fieldAllRatings            = "field.all_ratings"
    case fieldReview                = "field.review"
    case fieldPhoto                 = "field.photo"
    case fieldLocation              = "field.location"
    case fieldCity                  = "field.city"
    case fieldCities                = "field.cities"
    case fieldPosition              = "field.position"
    case fieldSelectArtist          = "field.select_artist"
    case fieldWhereSat              = "field.where_sat"
    case fieldAdmission             = "field.admission"
    case fieldBlock                 = "field.block"
    case fieldRow                   = "field.row"
    case fieldSeat                  = "field.seat"
    case fieldSortierung            = "field.sort"
    case fieldSortierungColon       = "field.sort_colon"
    case fieldTimeRange             = "field.time_range"
    case fieldArrivalTime           = "field.arrival_time"
    case fieldDisplayName           = "field.display_name"
    case fieldDisplayNameHint       = "field.display_name_hint"
    case fieldTitleOptional         = "field.title_optional"
    case fieldTitle                 = "field.title"
    case fieldVenueOrLocation       = "field.venue_or_location"
    
    // MARK: - Ticket
    case ticketTypes                = "ticket.types"
    case ticketCategories           = "ticket.categories"
    case ticketPrice                = "ticket.price"
    case ticketPriceColon           = "ticket.price_colon"
    case ticketInfo                 = "ticket.info"
    case ticketInfoAdd              = "ticket.info_add"
    case ticketProvider             = "ticket.provider"
    case ticketNumber               = "ticket.number_question"
    case ticketScanPhoto            = "ticket.scan_photo"
    case ticketSeatInfo             = "ticket.seat_info"
    case ticketCategoryQuestion     = "ticket.category_question"
    case ticketArtistQuestion       = "ticket.artist_question"   // "Was für ein Ticket hattest du für %@"
    case ticketGenericQuestion      = "ticket.generic_question"  // "Was für ein Ticket hattest du"
    
    // MARK: - Setlist
    case setlist                    = "setlist.title"
    case setlistAdded               = "setlist.added_songs"
    case setlistDeleteSong          = "setlist.delete_song"
    case setlistDeleteConfirm       = "setlist.delete_confirm"
    
    // MARK: - Travel / Journey
    case travelInfo                 = "travel.info"
    case travelDistance             = "travel.distance"
    case travelDistanceQuestion     = "travel.distance_question"
    case travelDuration             = "travel.duration"
    case travelDurationQuestion     = "travel.duration_question"
    case travelCost                 = "travel.cost"
    case travelCostQuestion         = "travel.cost_question"
    case travelTransport            = "travel.transport_question"
    case travelWaiting              = "travel.waiting"
    case travelTotal                = "travel.total"
    case travelTotalTime            = "travel.total_time"
    case travelSpentTickets         = "travel.spent_tickets"
    case travelSpentTravel          = "travel.spent_travel"
    case travelSpentHotels          = "travel.spent_hotels"
    case travelSpentTotal           = "travel.spent_total"
    case travelSummary              = "travel.summary"
    case travelTicketsSummary       = "travel.tickets_summary"
    
    // Travel mode descriptions (dynamic, see string(for:with:))
    case travelModeWalking          = "travel.mode_walking"
    case travelModeCar              = "travel.mode_car"
    case travelModeBike             = "travel.mode_bike"
    case travelModeTrain            = "travel.mode_train"
    case travelModePlane            = "travel.mode_plane"
    
    // Travel dynamic strings
    case travelDistanceWas          = "travel.distance_was"      // "Der Weg war %@ lang."
    case travelCostWas              = "travel.cost_was"          // "Die Anreise hat dich %@ gekostet."
    case travelDurationWas          = "travel.duration_was"      // "Die Reise hat %@ gedauert."
    case travelHotelCost            = "travel.hotel_cost"        // "Und für die Übernachtung hast du %@ gezahlt."
    case travelArrived              = "travel.arrived"           // "Du bist um %@ angekommen"
    
    // Hotel
    case hotelQuestion              = "hotel.question"
    case hotelCostQuestion          = "hotel.cost_question"
    case hotelStayed                = "hotel.stayed"             // Toggle label
    
    // MARK: - Onboarding
    case onboardingWelcome          = "onboarding.welcome"
    case onboardingTagline          = "onboarding.tagline"
    case onboardingClouds           = "onboarding.clouds"
    case onboardingFeature1Title    = "onboarding.feature1_title"
    case onboardingFeature1Desc     = "onboarding.feature1_desc"
    case onboardingFeature2Title    = "onboarding.feature2_title"
    case onboardingFeature2Desc     = "onboarding.feature2_desc"
    case onboardingFeature3Title    = "onboarding.feature3_title"
    case onboardingFeature3Desc     = "onboarding.feature3_desc"
    case onboardingFeature4Desc     = "onboarding.feature4_desc"
    case onboardingReady            = "onboarding.ready"
    
    // MARK: - Auth
    case authLogin                  = "auth.login"
    case authRegister               = "auth.register"
    case authLoginOrRegister        = "auth.login_or_register"
    case authNotLoggedIn            = "auth.not_logged_in"
    case authLoginSync              = "auth.login_sync"
    case authForgotPassword         = "auth.forgot_password"
    case authForgotPasswordDesc     = "auth.forgot_password_desc"
    case authNewPassword            = "auth.new_password"
    case authNewPasswordDesc        = "auth.new_password_desc"
    case authChangePassword         = "auth.change_password"
    case authFieldEmail             = "auth.field_email"
    case authFieldPassword          = "auth.field_password"
    case authFieldPasswordRepeat    = "auth.field_password_repeat"
    case authFieldNewPassword       = "auth.field_new_password"
    case authFieldNewPasswordRepeat = "auth.field_new_password_repeat"
    
    // MARK: - Buddies
    case buddiesNone                = "buddies.none"
    case buddiesLoading             = "buddies.loading"
    case buddiesLoadError           = "buddies.load_error"
    case buddiesMyCode              = "buddies.my_code"
    case buddiesCodeHint            = "buddies.code_hint"
    case buddiesShareCode           = "buddies.share_code"
    case buddiesLetFriendScan       = "buddies.let_friend_scan"
    case buddiesCodeNotFound        = "buddies.code_not_found"    // "Der Code \"%@\" ist keinem Account zugeordnet."
    case buddiesUserNotFound        = "buddies.user_not_found"
    case buddiesSearchUser          = "buddies.search_user"
    case buddiesRequestSent         = "buddies.request_sent"
    case buddiesNoRequests          = "buddies.no_requests"
    case buddiesIncoming            = "buddies.incoming"
    case buddiesOutgoing            = "buddies.outgoing"
    case buddiesAfterAccept         = "buddies.after_accept"      // "Sobald %@ akzeptiert, erscheint er in deiner Buddy-Liste."
    case buddiesTapToReply          = "buddies.tap_to_reply"
    
    // MARK: - Profile
    case profileLoading             = "profile.loading"
    case profileLoadError           = "profile.load_error"
    case profileCannotLoad          = "profile.cannot_load"
    case profileNameQuestion        = "profile.name_question"
    case profileNameHint            = "profile.name_hint"
    case profileImproveApp          = "profile.improve_app"
    case profilePrivacyHint         = "profile.privacy_hint"
    case profileAnalyticsHint       = "profile.analytics_hint"
    case profileSavedLocally        = "profile.saved_locally"
    case profileFAQ                 = "profile.faq"
    
    // MARK: - Sorting
    case sortDateNewest             = "sort.date_newest"
    case sortDateOldest             = "sort.date_oldest"
    case sortArtistAZ               = "sort.artist_az"
    case sortArtistZA               = "sort.artist_za"
    
    // MARK: - Premium
    case premiumTitle               = "premium.title"
    case premiumUnlockAll           = "premium.unlock_all"
    case premiumYourBenefits        = "premium.your_benefits"
    case premiumNowMember           = "premium.now_member"
    case premiumSavings             = "premium.savings"           // "Du sparst %@%%"
    case premiumBadgePopular        = "premium.badge_popular"
    case premiumBadgeOneTime        = "premium.badge_one_time"
    case premiumPerMonth            = "premium.per_month"
    case premiumNoRestoreFound      = "premium.no_restore_found"
    case premiumVerifyFailed        = "premium.verify_failed"
    
    // Premium features
    case featureUnlimited           = "feature.unlimited"
    case featureCloudSync           = "feature.cloud_sync"
    case featureNoAds               = "feature.no_ads"
    case featureAdvancedStats       = "feature.advanced_stats"
    case featureAdvancedFilters     = "feature.advanced_filters"
    case featureMultiplePhotos      = "feature.multiple_photos"
    case featureSetlistImport       = "feature.setlist_import"
    case featureTicketScanner       = "feature.ticket_scanner"
    case featureConcertNotes        = "feature.concert_notes"
    case featureConcertReminders    = "feature.concert_reminders"
    case featureExportData          = "feature.export_data"
    case featureShareSocial         = "feature.share_social"
    case featureAiRecommendations   = "feature.ai_recommendations"
    case featureCustomThemes        = "feature.custom_themes"
    case featurePrioritySupport     = "feature.priority_support"
    
    // Premium benefit descriptions
    case benefitUnlimited           = "benefit.unlimited"
    case benefitCloudSync           = "benefit.cloud_sync"
    case benefitNoAds               = "benefit.no_ads"
    case benefitAlwaysCancelable    = "benefit.always_cancelable"
    case benefitExclusive           = "benefit.exclusive"
    
    // Premium feature descriptions
    case descUnlimited              = "desc.unlimited"
    case descCloudSync              = "desc.cloud_sync"
    case descNoAds                  = "desc.no_ads"
    case descAdvancedStats          = "desc.advanced_stats"
    case descAdvancedFilters        = "desc.advanced_filters"
    case descMultiplePhotos         = "desc.multiple_photos"
    case descSetlistImport          = "desc.setlist_import"
    case descTicketScanner          = "desc.ticket_scanner"
    case descConcertNotes           = "desc.concert_notes"
    case descConcertReminders       = "desc.concert_reminders"
    case descExportData             = "desc.export_data"
    case descShareSocial            = "desc.share_social"
    case descAiRecommendations      = "desc.ai_recommendations"
    case descCustomThemes           = "desc.custom_themes"
    case descPrioritySupport        = "desc.priority_support"
    
    // MARK: - Map
    case mapTitle                   = "map.title"
    
    // MARK: - Spotify
    case spotifyNoPlaylists         = "spotify.no_playlists"
    case spotifyNoPlaylistsDesc     = "spotify.no_playlists_desc"
    case spotifyLoadingPlaylists    = "spotify.loading_playlists"
    case spotifySearchPlaylists     = "spotify.search_playlists"
    case spotifyFollowers           = "spotify.followers"        // "Follower: %d"
    
    // MARK: - Camera / Ticket Scan
    case cameraAccessDenied         = "camera.access_denied"
    case cameraAccessDeniedDesc     = "camera.access_denied_desc"
    case cameraPhotoAccess          = "camera.photo_access"
    case cameraPhotoHint            = "camera.photo_hint"
    case cameraScanHint             = "camera.scan_hint"
    case cameraRecognized           = "camera.recognized"
    case cameraScanTicket           = "camera.scan_ticket_desc"
    
    // MARK: - Loading / States
    case loading                    = "state.loading"
    case loadingData                = "state.loading_data"
    case queryRunning               = "state.query_running"
    case errorGeneric               = "state.error_generic"
    case errorSomethingWrong        = "state.error_something_wrong"
    case swipeForMore               = "state.swipe_for_more"
    
    // MARK: - Errors (user-facing)
    case errorInvalidFormat         = "error.invalid_format"
    case errorInvalidQr             = "error.invalid_qr"
    case errorInvalidImage          = "error.invalid_image"
    case errorPhotoLoad             = "error.photo_load"
    case errorProfileSave           = "error.profile_save"
    case errorProfileLoad           = "error.profile_load"
    case errorPasswordShort         = "error.password_short"
    case errorPasswordMismatch      = "error.password_mismatch"
    case errorResetLinkInvalid      = "error.reset_link_invalid"
    case errorRequestWithdraw       = "error.request_withdraw"
    case errorRequestDecline        = "error.request_decline"
    case errorRequestAccept         = "error.request_accept"
    case errorRequestSend           = "error.request_send"
    case errorFriendRemove          = "error.friend_remove"
    case errorCodeRenew             = "error.code_renew"
    case errorTicketRead            = "error.ticket_read"
    case errorConcertCreate         = "error.concert_create"
    case errorNoArtistName          = "error.no_artist_name"
    case errorNoTicketInfo          = "error.no_ticket_info"
    case errorDecryptionFailed      = "error.decryption_failed"
    case errorICloudWarning         = "error.icloud_warning"
    case errorDecryption_desc       = "error.decryption_desc"
    case errorEncryptionRestricted  = "error.encryption_restricted"
    case errorDeleteFailed          = "error.delete_failed"
    case errorUploadFailed          = "error.upload_failed"
    case errorImageCompress         = "error.image_compress"
    case errorNoText                = "error.no_text"
    case errorDataProcess           = "error.data_process"
    case errorNotFound              = "error.not_found"
    case errorUnauthorized          = "error.unauthorized"
    case errorAccessRestricted      = "error.access_restricted"
    case errorTrackingRestricted    = "error.tracking_restricted"
    case errorTrackingAllowed       = "error.tracking_allowed"
    case errorTrackingDenied        = "error.tracking_denied"
    case errorAccessAllowed         = "error.access_allowed"
    case errorAccessDenied          = "error.access_denied"
    
    // MARK: - Success Messages
    case successEmailSent           = "success.email_sent"
    case successEventSaved          = "success.event_saved"
    case successConcertDeleted      = "success.concert_deleted"
    case successPasswordChanged     = "success.password_changed"
    case successUpdatesSaved        = "success.updates_saved"
    case successConcertCreated      = "success.concert_created"
    case successPremium             = "success.premium"
    case successRequestSent         = "success.request_sent"
    
    // MARK: - Confirmation Dialogs
    case confirmReady               = "confirm.ready"
    
    // MARK: - Seat Types
    case seatTypeStanding           = "seat.standing"
    case seatTypeSitting            = "seat.sitting"
    case seatTypeVip                = "seat.vip"
    case seatTypeGoldenCircle       = "seat.golden_circle"
    case seatTypeDiamondCircle      = "seat.diamond_circle"
    case seatTypeUnknown            = "seat.unknown"
    case seatTypeNotDecided         = "seat.not_decided"
    
    // MARK: - Travel Mode Names
    case travelModeNameWalking      = "travel_mode.walking"
    case travelModeNameCar          = "travel_mode.car"
    case travelModeNameBike         = "travel_mode.bike"
    case travelModeNameTrain        = "travel_mode.train"
    case travelModeNamePlane        = "travel_mode.plane"
    
    // MARK: - Summary Sections
    case summaryArrivalCost         = "summary.arrival_cost"
    case summaryDistance            = "summary.distance"
    case summaryTravelTime          = "summary.travel_time"
    case summaryHotel               = "summary.hotel"
    
    // MARK: - Section Headers / Dividers
    case sectionImages              = "section.images"
    case sectionLocation            = "section.location"
    case sectionExperience          = "section.experience"
    case sectionAttendees           = "section.attendees"
    case sectionRating              = "section.rating"
    case sectionTravel              = "section.travel"
    case sectionSetlist             = "section.setlist"
    case sectionSupportActs         = "section.support_acts"
    case sectionTicket              = "section.ticket"
    case sectionTimes               = "section.times"
    case sectionMyTicket            = "section.my_ticket"
    case sectionMyImages            = "section.my_images"
    case sectionMyExperience        = "section.my_experience"
    case sectionMyTravel            = "section.my_travel"
    case sectionDetailPage          = "section.detail_page"
    
    // MARK: - Notifications
    case notificationBadge          = "notification.badge"
    case notificationBody           = "notification.body"        // "Du warst beim Konzert \"%@\" dabei."
}

// MARK: - SwiftUI Convenience

extension TextKey {
    /// Direkter Zugriff: Text(TextKey.homeTitle.localized)
    var localized: String {
        TextManager.shared.string(for: self)
    }
    
    func localized(with arguments: CVarArg...) -> String {
        TextManager.shared.string(for: self, with: arguments)
    }
}
